name: AgentScan

on:
  pull_request_target:
    types: [opened, reopened]

permissions:
  pull-requests: write
  contents: read

jobs:
  agentscan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: AgentScan
        uses: MatteoGabriele/agentscan-action@v1.3.0-beta.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-members: "matteogabriele"
          cache: true
